USE smartmeeting;

-- Fix team_invitations types: INT->BIGINT UNSIGNED, ENUM->VARCHAR, TIMESTAMP->DATETIME
ALTER TABLE team_invitations
  MODIFY id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  MODIFY team_id BIGINT UNSIGNED NOT NULL,
  MODIFY inviter_id BIGINT UNSIGNED NOT NULL,
  MODIFY invitee_id BIGINT UNSIGNED NOT NULL,
  MODIFY status VARCHAR(20) NOT NULL DEFAULT 'pending',
  MODIFY created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
